// Auto-generated LinkedIn standard industries list (V2 and legacy/deprecated)
export const LINKEDIN_INDUSTRIES = [
  "Accessible Architecture and Design",
  "Accessible Hardware Manufacturing",
  "Accommodation Services",
  "Accounting",
  "Abrasives and Nonmetallic Minerals Manufacturing",
  "Administration of Justice",
  "Administrative and Support Services",
  "Advertising Services",
  "Agricultural Chemical Manufacturing",
  "Air, Water, and Waste Program Management",
  "Airlines and Aviation",
  "Alternative Dispute Resolution",
  "Alternative Fuel Vehicle Manufacturing",
  "Alternative Medicine",
  "Ambulance Services",
  "Amusement Parks and Arcades",
  "Animal Feed Manufacturing",
  "Animation",
  "Animation and Post-production",
  "Apparel and Fashion",
  "Apparel Manufacturing",
  "Appliances, Electrical, and Electronics Manufacturing",
  "Architectural and Structural Metal Manufacturing",
  "Architecture & Planning",
  "Architecture and Planning",
  "Armed Forces",
  "Art Supplies",
  "Artists and Writers",
  "Arts and Crafts",
  "Artificial Rubber and Synthetic Fiber Manufacturing",
  "Audio and Video Equipment Manufacturing",
  "Automotive",
  "Aviation & Aerospace",
  "Aviation and Aerospace Component Manufacturing",
  "Baked Goods Manufacturing",
  "Banking",
  "Bars, Taverns, and Nightclubs",
  "Bed-and-Breakfasts, Hostels, Homestays",
  "Beverage Manufacturing",
  "Biomass Electric Power Generation",
  "Biotechnology",
  "Biotechnology Research",
  "Blockchain Services",
  "Blogs",
  "Boilers, Tanks, and Shipping Container Manufacturing",
  "Book and Periodical Publishing",
  "Book Publishing",
  "Breweries",
  "Broadcast Media Production and Distribution",
  "Building Construction",
  "Building Equipment Contractors",
  "Building Finishing Contractors",
  "Building Materials",
  "Building Structure and Exterior Contractors",
  "Business Content",
  "Business Consulting and Services",
  "Business Intelligence Platforms",
  "Business Supplies and Equipment",
  "Cable and Satellite Programming",
  "Capital Markets",
  "Caterers",
  "Chemical Manufacturing",
  "Chemical Raw Materials Manufacturing",
  "Child Day Care Services",
  "Chiropractors",
  "Circuses and Magic Shows",
  "Civic and Social Organizations",
  "Civil Engineering",
  "Claims Adjusting, Actuarial Services",
  "Climate Data and Analytics",
  "Climate Technology Product Manufacturing",
  "Coal Mining",
  "Collection Agencies",
  "Commercial and Industrial Equipment Rental",
  "Commercial and Industrial Machinery Maintenance",
  "Commercial Real Estate",
  "Communications Equipment Manufacturing",
  "Community Development and Urban Planning",
  "Community Services",
  "Computer Games",
  "Computer Hardware",
  "Computer Hardware Manufacturing",
  "Computer Networking",
  "Computer Networking Products",
  "Computer and Network Security",
  "Conservation Programs",
  "Construction",
  "Construction Hardware Manufacturing",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Goods Rental",
  "Consumer Services",
  "Correctional Institutions",
  "Cosmetics",
  "Cosmetology and Barber Schools",
  "Courts of Law",
  "Credit Intermediation",
  "Cutlery and Handtool Manufacturing",
  "Dairy",
  "Dairy Product Manufacturing",
  "Dance Companies",
  "Data Infrastructure and Analytics",
  "Data Security Software Products",
  "Defense & Space",
  "Defense and Space Manufacturing",
  "Dentists",
  "Design",
  "Design Services",
  "Desktop Computing Software Products",
  "Digital Accessibility Services",
  "Distilleries",
  "E-Learning",
  "E-Learning Providers",
  "Economic Programs",
  "Education",
  "Education Administration",
  "Education Administration Programs",
  "Education Management",
  "Electric Lighting Equipment Manufacturing",
  "Electric Power Generation",
  "Electric Power Transmission, Control, and Distribution",
  "Electrical Equipment Manufacturing",
  "Electronic and Precision Equipment Maintenance",
  "Embedded Software Products",
  "Emergency and Relief Services",
  "Engineering Services",
  "Entertainment",
  "Entertainment Providers",
  "Environmental Services",
  "Environmental Quality Programs",
  "Equipment Rental Services",
  "Executive Offices",
  "Executive Search Services",
  "Events Services",
  "Facilities Services",
  "Family Planning Centers",
  "Farming",
  "Farming, Ranching, Forestry",
  "Fashion Accessories Manufacturing",
  "Financial Services",
  "Fine Art",
  "Fine Arts Schools",
  "Fire Protection",
  "Fisheries",
  "Flight Training",
  "Food & Beverages",
  "Food Production",
  "Food and Beverage Manufacturing",
  "Food and Beverage Retail",
  "Food and Beverage Services",
  "Footwear and Leather Goods Repair",
  "Forestry and Logging",
  "Fossil Fuel Electric Power Generation",
  "Freight and Package Transportation",
  "Fuel Cell Manufacturing",
  "Fundraising",
  "Funds and Trusts",
  "Furniture",
  "Furniture and Home Furnishings Manufacturing",
  "Gambling Facilities and Casinos",
  "Geothermal Electric Power Generation",
  "Glass, Ceramics and Concrete Manufacturing",
  "Glass Product Manufacturing",
  "Golf Courses and Country Clubs",
  "Government Administration",
  "Government Relations",
  "Government Relations Services",
  "Graphic Design",
  "Ground Passenger Transportation",
  "Health Health Care",
  "Health and Human Services",
  "Health, Wellness and Fitness",
  "Higher Education",
  "Highway, Street, and Bridge Construction",
  "Historical Sites",
  "Holding Companies",
  "Home Health Care Services",
  "Horticulture",
  "Hospitality",
  "Hospitals",
  "Hospitals and Health Care",
  "Household Appliance Manufacturing",
  "Household and Institutional Furniture Manufacturing",
  "Household Services",
  "Housing and Community Development",
  "Housing Programs",
  "Human Resources",
  "Human Resources Services",
  "Hydroelectric Power Generation",
  "Import and Export",
  "Individual and Family Services",
  "Industrial Automation",
  "Industry Associations",
  "Information Services",
  "Information Technology and Services",
  "Information Technology Services",
  "IT Services and IT Consulting",
  "IT System Custom Software Development",
  "IT System Data Services",
  "IT System Design Services",
  "IT System Installation and Disposal",
  "IT System Operations and Maintenance",
  "IT System Testing and Evaluation",
  "IT System Training and Support",
  "Insurance",
  "Insurance Agencies and Brokerages",
  "Insurance Carriers",
  "Interior Design",
  "International Affairs",
  "International Trade and Development",
  "Internet News",
  "Internet Marketplace Platforms",
  "Internet Publishing",
  "Investment Advice",
  "Investment Banking",
  "Investment Management",
  "Janitorial Services",
  "Landscaping Services",
  "Language Schools",
  "Law Enforcement",
  "Law Practice",
  "Leasing Non-residential Real Estate",
  "Leasing Residential Real Estate",
  "Legal Services",
  "Legislative Offices",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Loan Brokers",
  "Logistics and Supply Chain",
  "Luxury Goods and Jewelry",
  "Luxury Goods & Jewelry",
  "Machinery Manufacturing",
  "Magnetic and Optical Media Manufacturing",
  "Management Consulting",
  "Manufacturing",
  "Maritime",
  "Maritime Transportation",
  "Market Research",
  "Marketing Services",
  "Marketing and Advertising",
  "Mattress and Blinds Manufacturing",
  "Measuring and Control Instrument Manufacturing",
  "Meat Products Manufacturing",
  "Mechanical or Industrial Engineering",
  "Medical Devices",
  "Medical and Diagnostic Laboratories",
  "Medical Equipment Manufacturing",
  "Medical Practices",
  "Mental Health Care",
  "Metal Ore Mining",
  "Metal Treatments",
  "Metal Valve, Ball, and Roller Manufacturing",
  "Military and International Affairs",
  "Mining",
  "Mobile Computing Software Products",
  "Mobile Food Services",
  "Mobile Gaming Apps",
  "Motor Vehicle Manufacturing",
  "Motor Vehicle Parts Manufacturing",
  "Movies and Sound Recording",
  "Movies, Videos and Sound",
  "Museums",
  "Museums, Historical Sites, and Zoos",
  "Music",
  "Music and Music-Related Services",
  "Musicians",
  "Nanotechnology Research",
  "Natural Gas Distribution",
  "Natural Gas Extraction",
  "Newspaper Publishing",
  "Non-profit Organization Management",
  "Non-profit Organizations",
  "Nonmetallic Mineral Mining",
  "Nonresidential Building Construction",
  "Nuclear Electric Power Generation",
  "Nursing Homes and Residential Care Facilities",
  "Office Administration",
  "Office Furniture and Fixtures Manufacturing",
  "Oil and Coal Product Manufacturing",
  "Oil Extraction",
  "Oil and Gas",
  "Oil, Gas, and Mining",
  "Online Audio and Video Media",
  "Online Media",
  "Online and Mail Order Retail",
  "Operations Consulting",
  "Optometrists",
  "Outpatient Care Centers",
  "Outsourcing/Offshoring",
  "Outsourcing and Offshoring Consulting",
  "Packaging and Containers",
  "Packaging and Containers Manufacturing",
  "Paint, Coating, and Adhesive Manufacturing",
  "Paper and Forest Products",
  "Paper and Forest Product Manufacturing",
  "Performers and Writers",
  "Performing Arts",
  "Performing Arts and Spectator Sports",
  "Periodical Publishing",
  "Personal Care Product Manufacturing",
  "Personal Care Services",
  "Personal and Laundry Services",
  "Pet Services",
  "Pharmaceutical Manufacturing",
  "Pharmaceuticals",
  "Philanthropy",
  "Philanthropic Fundraising Services",
  "Photography",
  "Physical, Occupational and Speech Therapists",
  "Physicians",
  "Pipeline Transportation",
  "Plastics Manufacturing",
  "Plastics and Rubber Product Manufacturing",
  "Political Organizations",
  "Postal Services",
  "Primary Metal Manufacturing",
  "Primary and Secondary Education",
  "Printing Services",
  "Professional Organizations",
  "Professional Training and Coaching",
  "Professional Services",
  "Program Development",
  "Public Assistance Programs",
  "Public Health",
  "Public Policy",
  "Public Policy Offices",
  "Public Relations",
  "Public Relations and Communications Services",
  "Public Safety",
  "Racetracks",
  "Radio and Television Broadcasting",
  "Rail Transportation",
  "Railroad Equipment Manufacturing",
  "Ranching",
  "Ranching and Fisheries",
  "Real Estate",
  "Real Estate Agents and Brokers",
  "Real Estate and Equipment Rental Services",
  "Recreational Facilities",
  "Regenerative Design",
  "Religious Institutions",
  "Renewable Energy Semiconductor Manufacturing",
  "Renewables & Environment",
  "Renewable Energy Power Generation",
  "Repair and Maintenance",
  "Research",
  "Research Services",
  "Residential Building Construction",
  "Restaurants",
  "Retail",
  "Retail Apparel and Fashion",
  "Retail Appliances, Electrical, and Electronic Equipment",
  "Retail Art Dealers",
  "Retail Art Supplies",
  "Retail Books and Printed News",
  "Retail Building Materials and Garden Equipment",
  "Retail Florists",
  "Retail Furniture and Home Furnishings",
  "Retail Gasoline",
  "Retail Groceries",
  "Retail Health and Personal Care Products",
  "Retail Luxury Goods and Jewelry",
  "Retail Motor Vehicles",
  "Retail Musical Instruments",
  "Retail Office Equipment",
  "Retail Office Supplies and Gifts",
  "Retail Recyclable Materials & Used Merchandise",
  "Reupholstery and Furniture Repair",
  "Robotics Engineering",
  "Rubber Products Manufacturing",
  "Savings Institutions",
  "School and Employee Bus Services",
  "Secretarial Schools",
  "Securities and Commodity Exchanges",
  "Security Guards and Patrol Services",
  "Security and Investigations",
  "Security Systems Services",
  "Semiconductors",
  "Semiconductor Manufacturing",
  "Services for Renewable Energy",
  "Services for the Elderly and Disabled",
  "Shipbuilding",
  "Shuttles and Special Needs Transportation Services",
  "Sightseeing Transportation",
  "Skiing Facilities",
  "Smart Meter Manufacturing",
  "Social Networking Platforms",
  "Soap and Cleaning Product Manufacturing",
  "Software Development",
  "Space Research and Technology",
  "Specialty Trade Contractors",
  "Spectator Sports",
  "Sporting Goods",
  "Sporting Goods Manufacturing",
  "Sports Teams and Clubs",
  "Sports and Recreation Instruction",
  "Staffing and Recruiting",
  "Steam and Air-Conditioning Supply",
  "Strategic Management Services",
  "Subdivision of Land",
  "Sugar and Confectionery Product Manufacturing",
  "Surveying and Mapping Services",
  "Taxi and Limousine Services",
  "Technical and Vocational Training",
  "Technology, Information and Internet",
  "Technology, Information and Media",
  "Telecommunications",
  "Temporary Help Services",
  "Telephone Call Centers",
  "Textile Manufacturing",
  "Theater Companies",
  "Think Tanks",
  "Tobacco",
  "Tobacco Manufacturing",
  "Translation and Localization",
  "Transportation Equipment Manufacturing",
  "Transportation Programs",
  "Transportation, Logistics, Supply Chain and Storage",
  "Transportation/Trucking/Railroad",
  "Travel Arrangements",
  "Truck Transportation",
  "Turned Products and Fastener Manufacturing",
  "Urban Transit Services",
  "Utilities",
  "Utilities Administration",
  "Vehicle Repair and Maintenance",
  "Venture Capital and Private Equity Principals",
  "Veterinary",
  "Veterinary Services",
  "Vocational Rehabilitation Services",
  "Warehousing",
  "Warehousing and Storage",
  "Waste Collection",
  "Waste Treatment and Disposal",
  "Water Supply and Irrigation Systems",
  "Water, Waste, Steam, and Air Conditioning Services",
  "Wellness and Fitness Services",
  "Wholesale",
  "Wholesale Alcoholic Beverages",
  "Wholesale Apparel and Sewing Supplies",
  "Wholesale Appliances, Electrical, and Electronics",
  "Wholesale Building Materials",
  "Wholesale Chemical and Allied Products",
  "Wholesale Computer Equipment",
  "Wholesale Drugs and Sundries",
  "Wholesale Food and Beverage",
  "Wholesale Footwear",
  "Wholesale Furniture and Home Furnishings",
  "Wholesale Hardware, Plumbing, Heating Equipment",
  "Wholesale Import and Export",
  "Wholesale Luxury Goods and Jewelry",
  "Wholesale Machinery",
  "Wholesale Metals and Minerals",
  "Wholesale Motor Vehicles and Parts",
  "Wholesale Paper Products",
  "Wholesale Petroleum and Petroleum Products",
  "Wholesale Photography Equipment and Supplies",
  "Wholesale Raw Farm Products",
  "Wholesale Recyclable Materials",
  "Wind Electric Power Generation",
  "Wine and Spirits",
  "Wineries",
  "Wood Product Manufacturing",
  "Writing and Editing",
  "Zoos and Botanical Gardens"
];
